FROM ubuntu:18.04
ARG PACKAGE_LOCATION


RUN apt update \
    && apt install -y g++ gcc libzmq3-dev libjsoncpp-dev python-dev libudev-dev llvm-4.0-dev wget lbzip2 cmake libboost-all-dev \
    && echo $PACKAGE_LOCATION \
    && mkdir aionr

WORKDIR /aionr
ADD $PACKAGE_LOCATION /aionr
ADD libs/jdk-11.0.1 /run/libs/jdk-11.0.1

ENV JAVA_HOME="/run/libs/jdk-11.0.1"
ENV LIBRARY_PATH="${JAVA_HOME}/lib/server"
ENV LD_LIBRARY_PATH="${LIBRARY_PATH}:/usr/local/lib:/run/libs" PATH="${PATH}:${JAVA_HOME}/bin"

ENTRYPOINT ["/bin/bash"]
CMD ["./mainnet.sh"]

EXPOSE 30303 8545 8546 8547 8008
